### ISSUE TITLE
Finding manual of previous versions 

### ISSUE THREAD

**Issue by jksull** [Al-Murphy/MungeSumstats#169]
Hi Al,

Thanks again for the awesome tool!

I was wondering if there is any way to access the manual for a previous version of MSS?  I have recently updated to V`1.9.15`, and while I understand that there is a newer version (`1.9.17`), I would first need to bump some other software to get that to work, and `1.9.15` seems stable and with many new features and fixes that I am excited to try out.

Furthermore, I find myself going to this manual: https://bioconductor.org/packages/release/bioc/manuals/MungeSumstats/man/MungeSumstats.pdf time and time again, it's incredibly helpful! I would like to pin the corresponding manual (for version `1.9.15`), but visiting the above link will always lead to the most current version.

Is there a way to find the manual for previous versions, so that I can make use of the manual without confusing features that are not actually implemented in the version I am using? 

Unless there is already a way to see older manuals, even if I was to update to the most recent version right now (`1.9.17`), I would need to make sure to download the manual and keep a history locally, and would need to do that continually in the future as I bump the version of the tool - so hosting different versions of the manual would be a great accessibility feature going forward.

Thanks in advance!

**Comment by Al-Murphy** [comment]
Hey! 

So there will have been no change in functions across those releases so personally I would just use the current release vignette and check with the R help documentation for MSS functions independently to see which parameters are there in your version (for example `?MungeSumstats::format_sumstats()`). This will give the same style of documentation to the manual.

So one other way would be to get the version of MSS from Github (see the different branches for the different releases) and then build the manual with `devtools` and the git cloned version of the package:

```
#path will let you save it anywhere locally
>devtools::build_manual(path='~/Downloads/')
Output written on Rd2.pdf (38 pages, 176919 bytes).
Transcript written on Rd2.log.
Saving output to ‘~/Downloads//MungeSumstats_1.10.1.pdf’ ...
Done
```

Alan.

**Comment by NathanSkene** [comment]
There is also the option of using the docker version, if you don’t want to update other packages while still using the latest version. The docker container builds automatically with each new release.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Al-Murphy** [comment]
Yes that's correct - a new version should be released with each push to our github through rworkflows and GHAs but this has been failing for the last few months (@bschilder, this is the issue we discussed).
