### ISSUE TITLE
different gwas column title to import

### ISSUE THREAD

**Issue by songlyzz** [Al-Murphy/MungeSumstats#195]
Hi Murphy,
  I using some GWAS sumstats by plink 1.9 or 2, the summary titile contain :
(1) SNP Allele1 Allele2  Freq1 FreqSE MinFreq MaxFreq    Weight Zscore       P Direction HetISq HetChiSq HetDf HetPVal CHR        BP
(2) "variant_id","chromosome","base_pair_location","effect_allele","other_allele","odds_ratio","p_value"
(3) "SNP","CHR","BP","A1","A2","OR","P"
(4) "ID","CHROM","POS","ALT","REF","or","PVAL"
How can I deal with it, just rename them to "SNP","CHR","BP","A1","A2","OR","P" and use function format_sumstats(path = XX,
                ref_genome = "GRCh37",
                infer_eff_direction=TRUE
) ?

**Comment by Al-Murphy** [comment]
Hi! So Mungesumstats uses a mapping file so should be able to pick up and differing names of the column headers no matter the standard used. Please try running your sumstats as is but feel free to reopen if there are any errors with column headers. Also worth reading the related documentation as I believe this is covered there (if not, let me know as it should be!).

Cheers,
Alan.
