### ISSUE TITLE
Question Regarding Additional Columns in GWAS Summary Statistics for MungeSumstats

### ISSUE THREAD

**Issue by LouChen-med** [Al-Murphy/MungeSumstats#197]
I have a question regarding the input format for MungeSumstats. Specifically, I would like to know if it's acceptable to include additional columns that are not part of the standard set listed in data("sumstatsColHeaders"). For example, I often add custom columns such as "ROW_NUMBER" and "ANNOTATION", which are not part of the essential columns (like SNP, CHR, BP, etc.) required by MungeSumstats.

Will including these extra columns affect the processing of the GWAS summary statistics, or does the package simply ignore them during analysis? 

Thank you for your assistance.

**Comment by Al-Murphy** [comment]
Hey!

Adding extra columns that are not listed in the columns to standardise (`data("sumstatsColHeaders")`) will not affect any processing of GWAS summary statistics. As you suggest, they will just be ignored and returned on output. Note that MSS will also not drop rows with missing values in these extra columns - if you want this functionality, you can add the column names into the vector input for `drop_na_cols` in `format_sumstats()` call or set just `drop_na_cols=NULL' which will check every input column for missing values.

Cheers,
Alan.

**Comment by LouChen-med** [comment]
Hello, thank you for your response. I would like to ask a few more questions:

1. Since I am using R 4.2.2, I can only download version 1.6.0 of MungeSumstats from Bioconductor. This version does not have the drop_na_cols option. Can I still use it? I typically use this package for liftover version conversion and adding SNPs. Will this affect the process?

2. In version 1.6.0 of MungeSumstats, the extra columns I mentioned earlier will not affect the GWAS processing, right?

Thank you very much for your further clarification.

**Comment by Al-Murphy** [comment]
Hi,

1.6.0 is now a very old version of MSS. To ensure it is bug free and has all the specified features, I would upgrade to the latest release version.

Thanks,
Alan.
