### ISSUE TITLE
Unable tor retrieve IEU GWAS summary stastics

### ISSUE THREAD

**Issue by karpat90** [Al-Murphy/MungeSumstats#199]
Hello!

I have installed the latest version of MungeSumstats (1.15.2) from BiocManager.

I tried retrieving IEU summary statistics and their metinformation:

metagwas <- MungeSumstats::find_sumstats(traits = c("parkinson","alzheimer"), 
                                    min_sample_size = 1000)

Collecting metadata from Open GWAS.
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server issue: 503
Unable to retrieve results from server. See status in the returned object and contact the developers if the problem persists.
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.

I suppose I need specify access_token as per Manual but I tried get_acces_token and R doesn't find the function.

Thank you for your help!

**Comment by Al-Murphy** [comment]
Hey!

So I get the same error and looking into it, it appears it's because the MRC IEU OpenGWAS API is down at https://gwas-api.mrcieu.ac.uk/, see below:

![image](https://github.com/user-attachments/assets/571fb48e-cdb0-4f71-9e52-78bf88998f79)

I've emailed the developers of the IEU Open GWAS project so hopefully they can work to rectify this. However, in the meantime, you can still [search on their website](https://gwas.mrcieu.ac.uk/datasets/?trait__icontains=parkinson), download any GWAS sumstats you like and still format with MSS. 

I'll leave this issue open to report back on this.

**Comment by Al-Murphy** [comment]
Okay so I heard back from the IEU GWAS developers and they have updated their access approach. I have added the new approach to MSS v1.15.3 dev version (available through bioconductor dev in a few days or straight from github now). I have updated the readme to give info on this but basically you have to sign up to get api access and create a token in R. Then it will work as before. See below for details:

To authenticate, you need to generate a token from the OpenGWAS website. The 
token behaves like a password, and it will be used to authorise the requests 
you make to the OpenGWAS API. Here are the steps to generate the token and then 
have `ieugwasr` automatically use it for your queries:
  
1. Login to https://api.opengwas.io/profile/
2. Generate a new token
3. Add `OPENGWAS_JWT=<token>` to your .Renviron file, thi can be edited in R by 
running `usethis::edit_r_environ()`
4. Restart your R session
5. To check that your token is being recognised, run 
`ieugwasr::get_opengwas_jwt()`. If it returns a long random string then you are 
authenticated.
6. To check that your token is working, run `ieugwasr::user()`. It will make a 
request to the API for your user information using your token. It should return 
a list with your user information. If it returns an error, then your token is 
not working.
7. Make sure you have submitted user information to increasse you API limit at
https://api.opengwas.io/profile/.


Feel free to reopen if you have any issues with this.
